theme: jekyll-theme-slate
title: Yongji Guan's Personal Website
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
