theme: jekyll-theme-slate
title: Welcome to Yongji Guan's Website
description: >
  Where there is a will, there is a way!
author :
  name : fullit
  email : lantoniotrento@gmail.com
  github : antoniotrento
  twitter : lantoniotrento
  feedburner : fullit
email: your-email@domain.com
header_page_refs: ['now', 'about', 'contact']
