theme: jekyll-theme-slate
title: Yongji Guan's Personal Website
email: your-email@domain.com
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.
lang: en-US
