theme: jekyll-theme-slate
title: <center>Welcome to Yongji Guan's Website</center>
description: >
  <p align="right">Where there is a will, there is a way!</p>
author :
  name : fullit
  email : lantoniotrento@gmail.com
  github : antoniotrento
  twitter : lantoniotrento
  feedburner : fullit
email: your-email@domain.com
header_page_refs: ['now', 'about', 'contact']
